# Generated by Django 4.0 on 2022-01-11 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(max_length=10)),
                ('source', models.CharField(max_length=60)),
                ('rhn', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('urlImg', models.CharField(max_length=1000)),
            ],
        ),
    ]
