# Generated by Django 4.0 on 2022-01-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField(max_length=10)),
                ('urlImg', models.CharField(max_length=1000)),
            ],
        ),
    ]
